---
#-------------------------------
# General Site Settings

title: Chin Hui
logo:
author: Ek Chin Hui
description: Portfolio page
email: ekchinhui@gmail.com
copyright: Copyright &copy; 2021 Ek Chin Hui
# Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/personal-site/about" }
  - { name: Portfolio, link: "/personal-site/portfolio" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Chin Hui <br> Software Developer

social:
  - { icon: "ti-github", link: "https://www.github.com/ekchinhui" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/ek-chin-hui/" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: "I am a Computer Science Student currently enrolled in National University of Singapore. </br>I am an explorer at heart and venture into a wide range of topics, fields and technologies, meaning there is little that doesn't pique my interest."

blurb-btn-link: "/personal-site/about"
blurb-btn-name: know more

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Java, color: "#bdecf6", value: "70%" }
  - { name: Python, color: "#fdb157", value: "90%" }
  - { name: HTML & CSS, color: "#9473e6", value: "80%" }
  - { name: React & Vue, color: "#ffbcaa", value: "40%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: System Integrator & Support,
      icon: "icon-1.png",
      date: "May 2021 - Present",
      organization: "Toppan Ecquaria",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Bachelors in Computer Science,
      date: "Present",
      organization: "National University of Singapore",
    }
  - {
      name: GCE A Levels,
      date: "2016",
      organization: "River Valley High School",
    }

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: ekchinhui@gmail.com
